[package]
name = "meshpit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = "4.5.26"
p2panda-core = "0.1.0"
p2panda-discovery = { version = "0.1.0", features = ["mdns"] }
p2panda-net = "0.1.0"
p2panda-store = "0.1.0"
p2panda-stream = "0.1.0"
p2panda-sync = { version = "0.1.0", features = ["log-sync"] }
serde = "1.0.217"
tokio = "1.43.0"
